[package]
name = "construct-user-service"
license = "AGPL-3.0-only"
version.workspace = true
edition.workspace = true

[dependencies]
construct-auth           = { path = "../construct-auth" }
construct-config         = { path = "../construct-config" }
construct-context        = { path = "../construct-context" }
construct-crypto         = { path = "../construct-crypto", features = ["full"] }
construct-db             = { path = "../construct-db" }
construct-error          = { path = "../construct-error", features = ["full"] }
construct-queue          = { path = "../construct-queue" }
construct-utils          = { path = "../construct-utils" }

# Optional APNs only used by UserServiceContext::to_app_context adapter
construct-apns           = { path = "../construct-apns" }

anyhow     = "1.0"
serde      = { version = "1.0", features = ["derive"] }
tokio      = { version = "1", features = ["sync"] }
tracing    = "0.1"
uuid       = { version = "1.11", features = ["v4"] }
